export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/1.jpeg",
    username: "Trần Văn An",
  },
  {
    id: 2,
    profilePicture: "assets/person/2.jpeg",
    username: "Hoàng Hải Bình",
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpeg",
    username: "Vũ Đức Hiếu",
  },
  {
    id: 4,
    profilePicture: "assets/person/4.jpeg",
    username: "Nguyễn Trung Kiên",
  },
  {
    id: 5,
    profilePicture: "assets/person/5.jpeg",
    username: "Bách Thành Long",
  },
  {
    id: 6,
    profilePicture: "assets/person/6.jpeg",
    username: "Phan Trí Dũng",
  },
  {
    id: 7,
    profilePicture: "assets/person/7.jpeg",
    username: "Trần Thị Dung",
  },
  {
    id: 8,
    profilePicture: "assets/person/8.jpeg",
    username: "Lê Minh Kiên",
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpeg",
    username: "Vũ Hải Nam",
  },
  {
    id: 10,
    profilePicture: "assets/person/10.jpeg",
    username: "Trần Quốc Trí",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Công ty TNHH ABC đăng tin tuyển nhân viên....",
    photo: "assets/post/1.jpeg",
    createdDate: "2024-05-08 08:00:02",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/post/2.jpeg",
    createdDate: "2024-02-08 08:00:00",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "",
    photo: "assets/post/3.jpeg",
    createdDate: "2024-01-08 08:00:00",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    createdDate: "2024-09-08 08:00:00",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    createdDate: "2024-08-08 08:00:00",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    createdDate: "2024-05-08 08:00:00",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "",
    photo: "assets/post/7.jpeg",
    createdDate: "2024-04-08 08:00:00",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    createdDate: "2024-02-08 08:00:00",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "",
    photo: "assets/post/9.jpeg",
    createdDate: "2024-11-08 08:00:00",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    desc: "",
    photo: "assets/post/10.jpeg",
    createdDate: "2024-09-08 08:00:00",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
